---
title: "A Bayesian Linear Mixed Model Analysis of the Kronmueller and Barr (2007) data using Stan"
author: "Shravan Vasishth and Douglas Bates"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{KB07 Bayesian data analysis}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r preliminaries,echo=FALSE,include=FALSE,cache=FALSE}
library(lme4)
library(RePsychLing)
library(knitr)
library(rstan)
library(parallel)
opts_chunk$set(comment=NA)
options(width=92,show.signif.stars = FALSE)
```

## Load data

```{r preparedata,echo=TRUE,eval=FALSE,cache=FALSE}
#load("../data/kb07.rda")
N<-dim(kb07)[1]
x_full <- model.matrix(~1+S+P+C+SP+SC+PC+SPC, data=kb07)

x_u_full <- model.matrix(~1+S+P+C+SP+SC+PC+SPC, data=kb07) 
x_w_full <-  model.matrix(~1+S+P+C+SP+SC+PC+SPC, data=kb07)

dat <- 
  list(x = x_full,
    x_u = x_u_full,
    x_w = x_w_full,
    RTtrunc = kb07$RTtrunc,
    subj = as.vector(as.integer(kb07$subj)),
    item = as.vector(as.integer(kb07$item)),
    N_coef = 8, ## no. of fixefs
    N_coef_u = 8, ## no. of subj ranefs
    N_coef_w = 8, ## no. of item ranefs
    N = nrow(kb07),
    I = nlevels(kb07$subj),
    K = nlevels(kb07$item))
```

## Maximal model analysis

```{r definemaxmodel,echo=TRUE,eval=FALSE,cache=FALSE}
kb07maxmodel_code<-"data {
  int<lower=1> N;
  real RTtrunc[N];  	 //outcome
  int<lower=1> I;		 //number of subjects
  int<lower=1> K;		 //number of items
  int<lower=1, upper=I> subj[N]; //subject id
  int<lower=1, upper=K> item[N]; //item id
  int<lower=0> N_coef_u;  
  int<lower=0> N_coef_w;
  int<lower=0> N_coef;
  matrix[N,N_coef] x;
  matrix[N,N_coef_u] x_u;
  matrix[N,N_coef_w] x_w;
}

parameters {
  vector[N_coef] beta;		// intercept and slope
  real<lower=0> sigma_e;	// residual sd
  vector<lower=0>[N_coef_u] sigma_u;	// subj sd
  vector<lower=0>[N_coef_w] sigma_w;	// item sd
  cholesky_factor_corr[N_coef_u] L_u;
  cholesky_factor_corr[N_coef_w] L_w;
  matrix[N_coef_u,I] z_u;
  matrix[N_coef_w,K] z_w;
}

transformed parameters {
      vector[N] fixeff;
      vector[N] raneff;
      vector[N] mu;
      matrix[N_coef_u,I]  u;         
      matrix[N_coef_w,K]  w;

      fixeff <- x * beta;   
      u <- (diag_pre_multiply(sigma_u,L_u) * z_u); // subj random effects
      w <- (diag_pre_multiply(sigma_w,L_w) * z_w); // item random effects
          
      for (i in 1:N)
        raneff[i] <- row(x_u,i) * col(u,subj[i])+ row(x_w,i) * col(w,item[i]);
      mu <- fixeff+raneff;
}

model {
  # priors:
  beta ~ normal(0,2000);
  sigma_e ~ normal(0,500);   // truncated normal, see parameters above
  sigma_u ~ normal(0,500);
  sigma_w ~ normal(0,500);
  L_u ~ lkj_corr_cholesky(4.0);
  L_w ~ lkj_corr_cholesky(4.0);
to_vector(z_u) ~ normal(0,1);
to_vector(z_w) ~ normal(0,1);
RTtrunc ~ normal(mu, sigma_e);  
}

generated quantities {
      matrix[N_coef_u,N_coef_u] Cor_u;
      matrix[N_coef_w,N_coef_w] Cor_w;

      Cor_u <- L_u * L_u';  //Correlations between random effects by subj
      Cor_w <- L_w * L_w';  //Correlations between random effects by item
}
"
```

```{r runmaxmodel,echo=TRUE,eval=FALSE,cache=FALSE}
## Set up model (no sampling done yet):
kb07maxmodel <- stan(model_code=kb07maxmodel_code, 
                   data = dat, 
                   chains = 0)
  
## Run model:
## (Adjust cores to match your computer)
sflist <- 
  mclapply(1:4, mc.cores = 4, 
           function(i) stan(fit = kb07maxmodel, 
                            data = dat,
                            iter=2000,
                            chains = 1, 
                            chain_id = i, 
                            refresh = -1))

## Note that this would be a huge file if saved:
KB07_stan <- sflist2stanfit(sflist)

KB07_results<- summary(KB07_stan,
                       pars=c("beta",
                              "sigma_u","sigma_w","sigma_e","Cor_u","Cor_w"),
                       probs = c(0.025,  0.975) ,digits_summary = 3)

KB07_maxresults<-round(KB07_results$summary,4)[,c(1,4,5)]
```

```{r printmaxmodel,echo=TRUE,eval=FALSE,cache=FALSE}
library(xtable)
print(xtable(KB07_maxresults),type="html")
```
<!-- html table generated in R 3.1.2 by xtable 1.7-4 package -->
<!-- Thu Mar 26 20:14:21 2015 -->
<table border=1>
<tr> <th>  </th> <th> mean </th> <th> 2.5% </th> <th> 97.5% </th>  </tr>
  <tr> <td align="right"> beta[1] </td> <td align="right"> 2175.64 </td> <td align="right"> 2019.95 </td> <td align="right"> 2328.94 </td> </tr>
  <tr> <td align="right"> beta[2] </td> <td align="right"> -66.37 </td> <td align="right"> -103.27 </td> <td align="right"> -31.80 </td> </tr>
  <tr> <td align="right"> beta[3] </td> <td align="right"> -331.84 </td> <td align="right"> -422.56 </td> <td align="right"> -232.45 </td> </tr>
  <tr> <td align="right"> beta[4] </td> <td align="right"> 79.02 </td> <td align="right"> 37.76 </td> <td align="right"> 118.69 </td> </tr>
  <tr> <td align="right"> beta[5] </td> <td align="right"> 21.45 </td> <td align="right"> -17.49 </td> <td align="right"> 58.76 </td> </tr>
  <tr> <td align="right"> beta[6] </td> <td align="right"> -18.89 </td> <td align="right"> -53.47 </td> <td align="right"> 15.63 </td> </tr>
  <tr> <td align="right"> beta[7] </td> <td align="right"> 4.94 </td> <td align="right"> -37.21 </td> <td align="right"> 46.66 </td> </tr>
  <tr> <td align="right"> beta[8] </td> <td align="right"> -23.75 </td> <td align="right"> -63.44 </td> <td align="right"> 13.77 </td> </tr>
  <tr> <td align="right"> sigma_u[1] </td> <td align="right"> 307.62 </td> <td align="right"> 246.83 </td> <td align="right"> 386.36 </td> </tr>
  <tr> <td align="right"> sigma_u[2] </td> <td align="right"> 49.81 </td> <td align="right"> 4.29 </td> <td align="right"> 100.70 </td> </tr>
  <tr> <td align="right"> sigma_u[3] </td> <td align="right"> 53.12 </td> <td align="right"> 4.78 </td> <td align="right"> 103.21 </td> </tr>
  <tr> <td align="right"> sigma_u[4] </td> <td align="right"> 70.48 </td> <td align="right"> 14.28 </td> <td align="right"> 121.09 </td> </tr>
  <tr> <td align="right"> sigma_u[5] </td> <td align="right"> 74.72 </td> <td align="right"> 14.15 </td> <td align="right"> 128.47 </td> </tr>
  <tr> <td align="right"> sigma_u[6] </td> <td align="right"> 28.69 </td> <td align="right"> 0.87 </td> <td align="right"> 74.21 </td> </tr>
  <tr> <td align="right"> sigma_u[7] </td> <td align="right"> 69.50 </td> <td align="right"> 10.29 </td> <td align="right"> 120.60 </td> </tr>
  <tr> <td align="right"> sigma_u[8] </td> <td align="right"> 35.47 </td> <td align="right"> 1.68 </td> <td align="right"> 82.84 </td> </tr>
  <tr> <td align="right"> sigma_w[1] </td> <td align="right"> 368.24 </td> <td align="right"> 288.01 </td> <td align="right"> 484.42 </td> </tr>
  <tr> <td align="right"> sigma_w[2] </td> <td align="right"> 30.47 </td> <td align="right"> 1.10 </td> <td align="right"> 75.75 </td> </tr>
  <tr> <td align="right"> sigma_w[3] </td> <td align="right"> 256.47 </td> <td align="right"> 191.90 </td> <td align="right"> 341.46 </td> </tr>
  <tr> <td align="right"> sigma_w[4] </td> <td align="right"> 49.32 </td> <td align="right"> 3.77 </td> <td align="right"> 107.05 </td> </tr>
  <tr> <td align="right"> sigma_w[5] </td> <td align="right"> 20.73 </td> <td align="right"> 0.92 </td> <td align="right"> 56.66 </td> </tr>
  <tr> <td align="right"> sigma_w[6] </td> <td align="right"> 33.49 </td> <td align="right"> 1.55 </td> <td align="right"> 86.48 </td> </tr>
  <tr> <td align="right"> sigma_w[7] </td> <td align="right"> 57.25 </td> <td align="right"> 5.23 </td> <td align="right"> 111.77 </td> </tr>
  <tr> <td align="right"> sigma_w[8] </td> <td align="right"> 53.84 </td> <td align="right"> 5.10 </td> <td align="right"> 108.05 </td> </tr>
  <tr> <td align="right"> sigma_e </td> <td align="right"> 654.10 </td> <td align="right"> 630.00 </td> <td align="right"> 679.32 </td> </tr>
   </table>

### Final model

```{r definedata,echo=TRUE,eval=FALSE,cache=FALSE}
x_full <- model.matrix(~1+S+P+C+SP+SC+PC+SPC, data=kb07)

x_u_fin <- model.matrix(~1, data=kb07) 
x_w_fin <-  model.matrix(~1+P, data=kb07)

dat <- 
  list(x = x_full,
    x_u = x_u_fin,
    x_w = x_w_fin,
    RTtrunc = kb07$RTtrunc,
    subj = as.vector(as.integer(kb07$subj)),
    item = as.vector(as.integer(kb07$item)),
    N_coef = 8, ## no. of fixefs
    N_coef_u = 1, ## no. of subj ranefs
    N_coef_w = 2, ## no. of item ranefs
    N = nrow(kb07),
    I = nlevels(kb07$subj),
    K = nlevels(kb07$item))
```

```{r definefinmodel,echo=TRUE,eval=FALSE,cache=FALSE}
kb07finmodel_code<-"data {
  int<lower=1> N;
  real RTtrunc[N];     //outcome
  int<lower=1> I;		 //number of subjects
  int<lower=1> K;		 //number of items
  int<lower=1, upper=I> subj[N]; //subject id
  int<lower=1, upper=K> item[N]; //item id
  int<lower=0> N_coef_u; // 1
  int<lower=0> N_coef_w; // 2
  int<lower=0> N_coef;   // 8
  matrix[N,N_coef] x;
  matrix[N,N_coef_u] x_u; //nx1
  matrix[N,N_coef_w] x_w; //nx2
}

parameters {
  vector[N_coef] beta;		// intercept and slope
  real<lower=0> sigma_e;	// residual sd
  vector<lower=0>[N_coef_u] sigma_u;	// subj sd
  vector<lower=0>[N_coef_w] sigma_w;	// item sd
  cholesky_factor_corr[N_coef_u] L_u;
  cholesky_factor_corr[N_coef_w] L_w;
  matrix[N_coef_u,I] z_u;
  matrix[N_coef_w,K] z_w;
}

transformed parameters {
      vector[N] fixeff;
      vector[N] raneff;
      vector[N] mu;
      matrix[N_coef_u,I]  u;         
      matrix[N_coef_w,K]  w;

      fixeff <- x * beta;   
      u <- (diag_pre_multiply(sigma_u,L_u) * z_u); // subj random effects
      w <- (diag_pre_multiply(sigma_w,L_w) * z_w); // item random effects
          
      for (i in 1:N)
        raneff[i] <- row(x_u,i) * col(u,subj[i])+ row(x_w,i) * col(w,item[i]);
      mu <- fixeff+raneff;
}

model {
  # priors:
  beta ~ normal(0,2000);
  sigma_e ~ normal(0,500);   // truncated normal
  sigma_u ~ normal(0,500);
  sigma_w ~ normal(0,500);
//  u ~ normal(0,sigma_u)
  L_u ~ lkj_corr_cholesky(4.0);
  L_w ~ lkj_corr_cholesky(4.0);
  to_vector(z_u) ~ normal(0,1);
  to_vector(z_w) ~ normal(0,1);
  RTtrunc ~ normal(mu, sigma_e);  
}

generated quantities {
      matrix[N_coef_u,N_coef_u] Cor_u;
      matrix[N_coef_w,N_coef_w] Cor_w;

      Cor_u <- L_u * L_u';  //Correlations between random effects by subj
      Cor_w <- L_w * L_w';  //Correlations between random effects by item
}
"
```

```{r runfinmodel,echo=TRUE,eval=FALSE,cache=FALSE}

kb07finmodel <- stan(model_code=kb07finmodel_code,data = dat,chains = 0)
  
## Adjust cores to match your computer:
sflist <- 
  mclapply(1:4, mc.cores = 4, 
           function(i) stan(fit = kb07finmodel, 
                            data = dat,
                            iter=3000,
                            chains = 1, 
                            chain_id = i, 
                            refresh = -1))

## note that this would be a huge file if saved:
KB07_finstan <- sflist2stanfit(sflist)

KB07_results<- summary(KB07_finstan,
                       pars=c("beta",
                              "sigma_u","sigma_w","sigma_e","Cor_u","Cor_w"),
                       probs = c(0.025,  0.975) ,digits_summary = 3)

KB07_finresults<-round(KB07_results$summary,4)[,c(1,4,5)]
```

```{r printfinmodel,echo=TRUE,eval=FALSE,cache=FALSE}
print(xtable(KB07_finresults),type="html")
```

<!-- html table generated in R 3.1.2 by xtable 1.7-4 package -->
<!-- Thu Mar 26 20:06:18 2015 -->
<table border=1>
<tr> <th>  </th> <th> mean </th> <th> 2.5% </th> <th> 97.5% </th>  </tr>
  <tr> <td align="right"> beta[1] </td> <td align="right"> 2173.75 </td> <td align="right"> 2021.70 </td> <td align="right"> 2330.83 </td> </tr>
  <tr> <td align="right"> beta[2] </td> <td align="right"> -67.14 </td> <td align="right"> -98.21 </td> <td align="right"> -35.84 </td> </tr>
  <tr> <td align="right"> beta[3] </td> <td align="right"> -333.31 </td> <td align="right"> -432.25 </td> <td align="right"> -236.12 </td> </tr>
  <tr> <td align="right"> beta[4] </td> <td align="right"> 79.13 </td> <td align="right"> 48.33 </td> <td align="right"> 109.87 </td> </tr>
  <tr> <td align="right"> beta[5] </td> <td align="right"> 21.75 </td> <td align="right"> -8.72 </td> <td align="right"> 53.10 </td> </tr>
  <tr> <td align="right"> beta[6] </td> <td align="right"> -18.61 </td> <td align="right"> -49.37 </td> <td align="right"> 13.06 </td> </tr>
  <tr> <td align="right"> beta[7] </td> <td align="right"> 5.40 </td> <td align="right"> -25.92 </td> <td align="right"> 36.37 </td> </tr>
  <tr> <td align="right"> beta[8] </td> <td align="right"> -23.98 </td> <td align="right"> -56.00 </td> <td align="right"> 7.97 </td> </tr>
  <tr> <td align="right"> sigma_u[1] </td> <td align="right"> 304.18 </td> <td align="right"> 241.98 </td> <td align="right"> 379.30 </td> </tr>
  <tr> <td align="right"> sigma_w[1] </td> <td align="right"> 369.44 </td> <td align="right"> 285.62 </td> <td align="right"> 477.28 </td> </tr>
  <tr> <td align="right"> sigma_w[2] </td> <td align="right"> 259.08 </td> <td align="right"> 194.44 </td> <td align="right"> 341.40 </td> </tr>
  <tr> <td align="right"> sigma_e </td> <td align="right"> 678.70 </td> <td align="right"> 656.25 </td> <td align="right"> 702.26 </td> </tr>
  <tr> <td align="right"> Cor_u[1,1] </td> <td align="right"> 1.00 </td> <td align="right"> 1.00 </td> <td align="right"> 1.00 </td> </tr>
  <tr> <td align="right"> Cor_w[1,1] </td> <td align="right"> 1.00 </td> <td align="right"> 1.00 </td> <td align="right"> 1.00 </td> </tr>
  <tr> <td align="right"> Cor_w[1,2] </td> <td align="right"> -0.56 </td> <td align="right"> -0.78 </td> <td align="right"> -0.26 </td> </tr>
  <tr> <td align="right"> Cor_w[2,1] </td> <td align="right"> -0.56 </td> <td align="right"> -0.78 </td> <td align="right"> -0.26 </td> </tr>
  <tr> <td align="right"> Cor_w[2,2] </td> <td align="right"> 1.00 </td> <td align="right"> 1.00 </td> <td align="right"> 1.00 </td> </tr>
   </table>


